# coding: utf-8

from __future__ import absolute_import
from datetime import date, datetime  # noqa: F401

from typing import List, Dict  # noqa: F401

from swagger_server.models.base_model_ import Model
from swagger_server import util


class DataInner(Model):
    """NOTE: This class is auto generated by the swagger code generator program.

    Do not edit the class manually.
    """

    def __init__(self, _date: str=None, value: float=None):  # noqa: E501
        """DataInner - a model defined in Swagger

        :param _date: The _date of this DataInner.  # noqa: E501
        :type _date: str
        :param value: The value of this DataInner.  # noqa: E501
        :type value: float
        """
        self.swagger_types = {
            '_date': str,
            'value': float
        }

        self.attribute_map = {
            '_date': 'date',
            'value': 'value'
        }

        self.__date = _date
        self._value = value

    @classmethod
    def from_dict(cls, dikt) -> 'DataInner':
        """Returns the dict as a model

        :param dikt: A dict.
        :type: dict
        :return: The Data_inner of this DataInner.  # noqa: E501
        :rtype: DataInner
        """
        return util.deserialize_model(dikt, cls)

    @property
    def _date(self) -> str:
        """Gets the _date of this DataInner.


        :return: The _date of this DataInner.
        :rtype: str
        """
        return self.__date

    @_date.setter
    def _date(self, _date: str):
        """Sets the _date of this DataInner.


        :param _date: The _date of this DataInner.
        :type _date: str
        """

        self.__date = _date

    @property
    def value(self) -> float:
        """Gets the value of this DataInner.


        :return: The value of this DataInner.
        :rtype: float
        """
        return self._value

    @value.setter
    def value(self, value: float):
        """Sets the value of this DataInner.


        :param value: The value of this DataInner.
        :type value: float
        """

        self._value = value
